// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDU9dFmr7zqL0BoeT_DjkW-VuZAWrFL4k',
    appId: '1:883871368145:web:1235894a7a3917b4a356f0',
    messagingSenderId: '883871368145',
    projectId: 'greenshare-9b344',
    authDomain: 'greenshare-9b344.firebaseapp.com',
    storageBucket: 'greenshare-9b344.firebasestorage.app',
    measurementId: 'G-5S3J7KMT99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc5bs8DNmjiXOsEpTqLK8fSyt8aAgSVhk',
    appId: '1:883871368145:android:d5f39f97510f4134a356f0',
    messagingSenderId: '883871368145',
    projectId: 'greenshare-9b344',
    storageBucket: 'greenshare-9b344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQQqTzGnhhulYh5VmwkwJYk-B7rtvEd2E',
    appId: '1:883871368145:ios:50f3c26cafc44411a356f0',
    messagingSenderId: '883871368145',
    projectId: 'greenshare-9b344',
    storageBucket: 'greenshare-9b344.firebasestorage.app',
    iosBundleId: 'com.greenshare.greenShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQQqTzGnhhulYh5VmwkwJYk-B7rtvEd2E',
    appId: '1:883871368145:ios:50f3c26cafc44411a356f0',
    messagingSenderId: '883871368145',
    projectId: 'greenshare-9b344',
    storageBucket: 'greenshare-9b344.firebasestorage.app',
    iosBundleId: 'com.greenshare.greenShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDU9dFmr7zqL0BoeT_DjkW-VuZAWrFL4k',
    appId: '1:883871368145:web:97659b9592c982c4a356f0',
    messagingSenderId: '883871368145',
    projectId: 'greenshare-9b344',
    authDomain: 'greenshare-9b344.firebaseapp.com',
    storageBucket: 'greenshare-9b344.firebasestorage.app',
    measurementId: 'G-CX4MZBHSTJ',
  );
}
