import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:green_share/services/ai_service.dart';
import 'package:green_share/services/database_service.dart';
import 'package:green_share/models/item_model.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:green_share/screens/post/location_picker_screen.dart';
import 'package:latlong2/latlong.dart';
import 'package:geolocator/geolocator.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

class PostItemScreen extends StatefulWidget {
  const PostItemScreen({super.key});

  @override
  State<PostItemScreen> createState() => _PostItemScreenState();
}

class _PostItemScreenState extends State<PostItemScreen> {
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _categoryController = TextEditingController();
  
  String _type = 'Donate';
  String _condition = 'Good';
  final List<String> _conditions = ['New', 'Good', 'Fair', 'Poor'];
  
  LatLng? _selectedLocation;
  XFile? _imageFile;
  final ImagePicker _picker = ImagePicker();
  final AIService _aiService = AIService();
  final DatabaseService _databaseService = DatabaseService();
  bool _isProcessingImage = false;
  bool _isUploading = false;
  bool _isLoadingLocation = false;

  @override
  void initState() {
    super.initState();
    _autoLocateUser();
  }

  Future<void> _autoLocateUser() async {
    if (FirebaseAuth.instance.currentUser == null) return;
    
    setState(() => _isLoadingLocation = true);
    bool serviceEnabled;
    LocationPermission permission;

    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Location services are disabled. Please enable GPS in your device to auto-detect your location.')),
        );
        setState(() => _isLoadingLocation = false);
      }
      if (!kIsWeb) {
        await Geolocator.openLocationSettings();
      }
      return;
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Location permission denied. Please allow location access to auto-detect your location.')),
          );
          setState(() => _isLoadingLocation = false);
        }
        return;
      }
    }
    
    if (permission == LocationPermission.deniedForever) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Location permissions are permanently denied. Please enable them in your device settings.')),
        );
        setState(() => _isLoadingLocation = false);
      }
      return;
    }

    try {
      Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high,
      );
      
      if (mounted) {
        setState(() {
          _selectedLocation = LatLng(position.latitude, position.longitude);
          _isLoadingLocation = false;
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Failed to auto-detect location. You can still pick it manually.')),
        );
        setState(() => _isLoadingLocation = false);
      }
    }
  }

  Future<void> _pickImage() async {
    final pickedFile = await _picker.pickImage(source: ImageSource.gallery);
    if (pickedFile != null) {
      setState(() {
        _imageFile = pickedFile;
        _isProcessingImage = true;
      });
      
      final category = await _aiService.classifyImage(pickedFile);
      
      setState(() {
        _isProcessingImage = false;
        if (category != null) {
          _categoryController.text = category;
        }
      });
    }
  }

  Future<void> _submitPost() async {
    if (_titleController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a title')),
      );
      return;
    }

    setState(() {
      _isUploading = true;
    });

    try {
      final userId = FirebaseAuth.instance.currentUser?.uid ?? 'anonymous_user';
      List<String> uploadedImageUrls = [];

      if (_imageFile != null) {
        final fileName = '${DateTime.now().millisecondsSinceEpoch}_${_imageFile!.name}';
        final url = await _databaseService.uploadImage(File(_imageFile!.path), 'item_images/$fileName');
        if (url != null) {
          uploadedImageUrls.add(url);
        }
      }

      final item = ItemModel(
        id: '', // Will be generated by Firestore
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim(),
        type: _type,
        category: _categoryController.text.trim().isNotEmpty ? _categoryController.text.trim() : 'Other',
        condition: _condition,
        imageUrls: uploadedImageUrls,
        ownerId: userId,
        postedAt: DateTime.now(),
        location: _selectedLocation != null ? 'Selected on Map' : 'Unknown Location',
        latitude: _selectedLocation?.latitude,
        longitude: _selectedLocation?.longitude,
        status: 'available',
      );

      await _databaseService.addItem(item);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Item posted successfully!')),
        );
        
        // Clear form
        _titleController.clear();
        _descriptionController.clear();
        _categoryController.clear();
        setState(() {
          _imageFile = null;
          _selectedLocation = null;
          _isUploading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error posting item: $e')),
        );
        setState(() {
          _isUploading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final currentUserId = FirebaseAuth.instance.currentUser?.uid;

    if (currentUserId == null) {
      return Scaffold(
        appBar: AppBar(
          title: const Text('Post Item'),
          automaticallyImplyLeading: false,
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(Icons.add_circle_outline, size: 60, color: Colors.grey.shade400),
              const SizedBox(height: 16),
              const Text(
                'Ready to share?',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.black87),
              ),
              const SizedBox(height: 8),
              Text(
                'Please log in or create an account to post items.',
                style: TextStyle(fontSize: 14, color: Colors.grey.shade600),
              ),
            ],
          ),
        ),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: const Text('Post Item'),
        automaticallyImplyLeading: false, // Don't show back button inside tab bar
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                ChoiceChip(
                  label: const Text('Donate'),
                  selected: _type == 'Donate',
                  onSelected: (val) {
                    if (val) setState(() => _type = 'Donate');
                  },
                ),
                const SizedBox(width: 16),
                ChoiceChip(
                  label: const Text('Request'),
                  selected: _type == 'Request',
                  onSelected: (val) {
                    if (val) setState(() => _type = 'Request');
                  },
                ),
              ],
            ),
            const SizedBox(height: 24),
            GestureDetector(
              onTap: _pickImage,
              child: Container(
                height: 200,
                decoration: BoxDecoration(
                  color: Colors.grey.shade200,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: Colors.grey.shade400, style: BorderStyle.none),
                ),
                child: _imageFile != null
                    ? ClipRRect(
                        borderRadius: BorderRadius.circular(16),
                        child: Image.file(File(_imageFile!.path), fit: BoxFit.cover),
                      )
                    : const Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.add_a_photo, size: 50, color: Colors.grey),
                          SizedBox(height: 8),
                          Text('Tap to add photo', style: TextStyle(color: Colors.grey)),
                        ],
                      ),
              ),
            ),
            const SizedBox(height: 16),
            if (_isProcessingImage)
              const Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2)),
                  SizedBox(width: 8),
                  Text('AI interpreting image...'),
                ],
              ),
            const SizedBox(height: 16),
            TextField(
              controller: _titleController,
              decoration: const InputDecoration(labelText: 'Title'),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _categoryController,
              decoration: const InputDecoration(labelText: 'Category (Auto-filled by AI)'),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _descriptionController,
              decoration: const InputDecoration(labelText: 'Description'),
              maxLines: 4,
            ),
            const SizedBox(height: 16),
            if (_type == 'Donate')
              DropdownButtonFormField<String>(
                initialValue: _condition,
                decoration: const InputDecoration(labelText: 'Condition'),
                items: _conditions.map((c) {
                  return DropdownMenuItem(value: c, child: Text(c));
                }).toList(),
                onChanged: (val) {
                  if (val != null) setState(() => _condition = val);
                },
              ),
            const SizedBox(height: 16),
            ListTile(
              contentPadding: EdgeInsets.zero,
              leading: const Icon(Icons.location_on, color: Colors.green),
              title: Text(_selectedLocation == null 
                  ? (_isLoadingLocation ? 'Locating...' : 'Select Location') 
                  : 'Location Selected'),
              subtitle: Text(_selectedLocation == null 
                  ? (_isLoadingLocation ? 'Getting current location...' : 'Tap to choose on map') 
                  : '${_selectedLocation!.latitude.toStringAsFixed(4)}, ${_selectedLocation!.longitude.toStringAsFixed(4)}'),
              trailing: _isLoadingLocation 
                  ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2))
                  : const Icon(Icons.chevron_right),
              onTap: _isLoadingLocation ? null : () async {
                final LatLng? picked = await Navigator.of(context).push(
                  MaterialPageRoute(builder: (_) => const LocationPickerScreen()),
                );
                if (picked != null) {
                  setState(() {
                    _selectedLocation = picked;
                  });
                }
              },
            ),
            const SizedBox(height: 32),
            _isUploading
                ? const Center(child: CircularProgressIndicator())
                : ElevatedButton(
                    onPressed: _submitPost,
                    child: const Text('Post'),
                  ),
          ],
        ),
      ),
    );
  }
}
